sudo: false
language: php
php:
  - 7.0
  - 7.1
  - 7.2
env:
  global:
    - ES_VERSION=5.6.8 ES_DOWNLOAD_URL=https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  matrix:
    - SYMFONY="~3.0"
    - SYMFONY="~3.1"
    - SYMFONY="~3.2"
    - SYMFONY="~3.3"
    - SYMFONY="~3.4"
    - SYMFONY="~4.0"
matrix:
  allow_failures:
    - php: 7.2
install:
  - wget ${ES_DOWNLOAD_URL}
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz
  - ./elasticsearch-${ES_VERSION}/bin/elasticsearch -d
before_script:
  - if [ "$SYMFONY" != "~4.0" ]; then composer require --no-update symfony/symfony:${SYMFONY}; fi
  - composer install --no-interaction --prefer-dist
script:
  - wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
  - vendor/bin/phpunit --coverage-clover=coverage.clover
  - vendor/bin/phpcs -p --standard=PSR2 --ignore=vendor/,Tests/app/ ./
after_script:
  - travis_retry php vendor/bin/coveralls